kind: Service
name: bigmyx
spec:
  path_user_role: jwt.user_role  # how to fetch profile
  path_user_name: jwt.user_name  # optional
  polling_interval_schema: 300
  polling_interval_profile: 10
  schema_files:
    - schema.graphql
  rate_limit:
    credits_per_type:
      User: 10
  validation:
    alias_name: "^[a-zA-Z]+$"
    directive_name: "^[a-zA-Z]+$"
    operation_name: "^[a-zA-Z0-9]+$"
    arguments:
      String: "^[a-zA-Z]+$"
  profiles:
  - name: guest
    max_depth: 10
    max_height: 10
    require_operation_name: true
    max_request_size_bytes: 512000
    max_response_size_bytes: 2048000
    rate_limit:
      mode: static
      header_output: true
      extension_output: true
      calls_per_minute: 100
      calls_per_hour: 1000
      credits_per_minute: 1000
      credits_per_hour: 10000
    #access:
    #  config: access/guest.inigo
    #  introspection: PARTIAL